import fs from 'node:fs/promises';
import path from 'node:path';
import MarkdownIt from 'markdown-it';
import anchor from 'markdown-it-anchor';
import footnote from 'markdown-it-footnote';
import katex from 'markdown-it-katex';

const root=process.cwd();
const postsDir=path.join(root,'posts');
const blogDir=path.join(root,'blog');
const cfg=JSON.parse(await fs.readFile(path.join(root,'site.config.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.replace(/\.md$/i,'');
const tags=a=>(a||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');
const tagMeta=a=>(a||[]).map(t=>`<span>#${esc(t)}</span>`).join('');
const external=h=>/^https?:\/\//.test(h||'');
function nav(active){return `<header class="topbar"><div class="wrap topbar__inner"><a class="brand" href="/"><span class="brand__mark">${esc(cfg.site.brand)}<span class="brand__dot">.</span></span><span class="brand__sub">${esc(cfg.site.brandSub)}</span></a><nav class="nav">${cfg.nav.map(([t,h])=>`<a class="${h===active?'is-active':''}" href="${esc(h)}"${external(h)?' target="_blank" rel="noreferrer"':''}>${esc(t)}</a>`).join('')}</nav></div></header>`}
function head(title,desc=''){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(desc||cfg.site.description)}"><title>${esc(title)} · ${esc(cfg.site.title)}</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/post-renderer.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"></head><body><div class="progress"></div>`}
function foot(extra=''){return `<footer class="footer"><div class="wrap footer__inner"><span>${esc(cfg.site.copyright)}</span><span>${extra||'<a href="/blog/">Blog</a> / <a href="/about/">About</a>'}</span></div></footer><script src="/assets/site.js"></script></body></html>`}
function card(x,link=''){let m=x[0],t=x[1],d=x[2],h=typeof x[3]==='string'?x[3]:'',ta=Array.isArray(x[3])?x[3]:x[4];let open=link||h;return `${open?`<a class="card" href="${esc(open)}"${external(open)?' target="_blank" rel="noreferrer"':''}>`:'<div class="card">'}<div class="card__meta"><span>${esc(m)}</span></div><h3>${esc(t)}</h3><p>${esc(d)}</p><div class="tags">${tags(ta)}</div>${open?'</a>':'</div>'}`}
function pageWrap(active,title,desc,main,extra){return head(title,desc)+nav(active)+main+foot(extra)}
function meta(src){if(!src.startsWith('---\n'))return[{},src];let e=src.indexOf('\n---\n',4);if(e<0)return[{},src];let data={};for(let line of src.slice(4,e).split('\n')){let p=line.indexOf(':');if(p<0)continue;let k=line.slice(0,p).trim(),v=line.slice(p+1).trim();if(v.startsWith('[')&&v.endsWith(']'))v=v.slice(1,-1).split(',').map(x=>x.trim().replace(/^['"]|['"]$/g,'')).filter(Boolean);else v=v.replace(/^['"]|['"]$/g,'');data[k]=v}return[data,src.slice(e+5)]}
function infer(file,data,text){let id=slug(file);let title=data.title||text.match(/^#\s+(.+)$/m)?.[1]||id;let description=data.description||text.replace(/[#*_`>\[\]$]/g,'').split('\n').find(x=>x.trim())||title;let date=data.date||'Post';let ta=Array.isArray(data.tags)?data.tags:['笔记'];return{id,title,description,date,tags:ta}}
const md=new MarkdownIt({html:true,linkify:true,typographer:true}).use(anchor,{slugify:s=>String(s).trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'')}).use(footnote).use(katex,{throwOnError:false,errorColor:'#d33'});
md.renderer.rules.fence=(tokens,idx)=>{let token=tokens[idx],lang=esc((token.info||'text').trim().split(/\s+/)[0]||'text'),code=esc(token.content);return `<div class="code-card"><div class="code-card__bar"><span class="code-card__lang">${lang}</span><span class="code-card__hint">scroll</span></div><pre><code class="language-${lang}">${code}</code></pre></div>`};
await fs.rm(blogDir,{recursive:true,force:true});await fs.mkdir(blogDir,{recursive:true});
const files=(await fs.readdir(postsDir)).filter(f=>f.endsWith('.md')&&!f.startsWith('_'));
const posts=[];
for(const file of files){let raw=await fs.readFile(path.join(postsDir,file),'utf8');let[data,content]=meta(raw);let item=infer(file,data,content);let out=path.join(blogDir,item.id);await fs.mkdir(out,{recursive:true});let body=md.render(content);let main=`<main class="render-shell"><a class="back" href="/blog/">← 返回文章列表</a><header class="render-head"><span class="eyebrow">${esc(item.date)}</span><h1>${esc(item.title)}</h1><p class="render-desc">${esc(item.description)}</p><div class="render-meta">${tagMeta(item.tags)}</div><div class="render-actions"><a class="btn" href="/posts/${esc(file)}">查看原文文件</a></div></header><article class="render-body">${body}</article></main>`;await fs.writeFile(path.join(out,'index.html'),pageWrap('/blog/',item.title,item.description,main,'<a href="/blog/">Blog</a>'));posts.push(item)}
posts.sort((a,b)=>String(b.date).localeCompare(String(a.date)));
let postCards=posts.map(p=>`<a class="card" href="/blog/${esc(p.id)}/"><div class="card__meta"><span>${esc(p.date)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="tags">${tags(p.tags)}</div></a>`).join('');
let home=cfg.home,stat=home.stats.map(([l,v])=>`<div class="stat"><span>${esc(l)}</span><b>${esc(v==='auto'?posts.length:v)}</b></div>`).join(''),actions=home.actions.map(([t,h,p])=>`<a class="btn ${p?'btn--primary':''}" href="${esc(h)}">${esc(t)}</a>`).join('');
await fs.writeFile(path.join(root,'index.html'),pageWrap('/',cfg.site.title,cfg.site.description,`<main><section class="hero"><div class="wrap hero__grid"><div><span class="eyebrow">${esc(home.eyebrow)}</span><h1>${esc(home.title)}</h1><p class="hero__lead">${esc(home.lead)}</p><div class="hero__actions">${actions}</div></div><aside class="stat-card"><p class="stat-card__title">Archive</p><div class="stats">${stat}</div></aside></div></section><section class="band"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Blog</span><h2>文章区</h2></div><p>文章列表由 posts 目录自动生成，不在首页写死。</p></div><div class="grid grid--3">${postCards}</div></div></section></main>`));
await fs.writeFile(path.join(blogDir,'index.html'),pageWrap('/blog/','文章','文章归档',`<main><section class="page-head wrap"><span class="eyebrow">Archive</span><h1>文章</h1><p>直接把 Markdown 文件放进 posts 目录即可生成文章页；标题、简介和标签会自动推断，必要时再用 frontmatter 覆盖。</p></section><section class="article-list wrap"><div class="grid grid--3">${postCards}</div></section></main>`,`${posts.length} posts`));
let about=cfg.about,aboutCards=about.cards.map(x=>card(x)).join(''),ms=about.milestones.map(x=>card(x)).join('');
await fs.mkdir(path.join(root,'about'),{recursive:true});
await fs.writeFile(path.join(root,'about/index.html'),pageWrap('/about/','关于',about.lead,`<main><section class="page-head wrap"><span class="eyebrow">${esc(about.eyebrow)}</span><h1>${esc(about.title)}</h1><p>${esc(about.lead)}</p></section><section class="band"><div class="wrap grid grid--2">${aboutCards}</div></section><section class="band band--2"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Milestones</span><h2>成长记录</h2></div><p>成长记录来自 site.config.json，不在页面里写死。</p></div><div class="grid grid--3">${ms}</div></div></section></main>`));
let prj=cfg.projects,featured=prj.featured.map(x=>card(x)).join(''),dirs=prj.directions.map(x=>card(x)).join('');
await fs.mkdir(path.join(root,'projects'),{recursive:true});
await fs.writeFile(path.join(root,'projects/index.html'),pageWrap('/projects/','项目',prj.lead,`<main><section class="page-head wrap"><span class="eyebrow">${esc(prj.eyebrow)}</span><h1>${esc(prj.title)}</h1><p>${esc(prj.lead)}</p></section><section class="band"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Featured</span><h2>核心项目</h2></div><p>项目卡片来自 site.config.json。</p></div><div class="grid grid--3">${featured}</div></div></section><section class="band band--2"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Map</span><h2>项目方向</h2></div><p>方向卡片来自 site.config.json。</p></div><div class="grid grid--3">${dirs}</div></div></section></main>`));
console.log(`built ${posts.length} posts and generated all pages from site.config.json`);
